package Configurations;

public class BuildingNames {

    public static String [] buildingNames = {
            "333 West Wacker Drive", "150 N Riverside Plaza", "One South Dearborn",
            "Lake Shore Place", "Ravenswood Professional Bldg", "191 N Wacker Building",
            "USG Building", "Midway Office Bldg", "1907 N Milwaukee Ave", "string",
            "PepsiCo Tower", "6114 W North Ave", "225 W Illinois St", "CDW Plaza",
            "111 South Wacker", "222 North LaSalle", "Hyatt Center", "One North Franklin",
            "123 North Wacker Drive", "303 West Madison", "101 North Wacker",
            "Aon Center", "333 S Wabash Ave", "225 West Wacker", "Test Mike",
            "20 N Clark St", "Willis Tower", "300 South Riverside Plaza",
            "ABN AMRO Plaza", "200 South Michigan", "311 W Monroe St", "180 N LaSalle",
            "190 South LaSalle", "International Tower", "200 South Wacker",
            "303 Wacker Building", "70 W Madison", "One South Wacker", "Hartford Plaza",
            "222 S Riverside Plaza", "10 South Riverside Plaza", "125 S Wacker Drive",
            "108 W Grand Ave", "The Old Post Office", "350 W Mart Center",
            "3257 N Sheffield Ave", "One North Dearborn", "1165 North Clark",
            "John Hancock Center", "600 West Chicago", "AT&T Corporate Center",
            "Citigroup Center", "Board of Trade", "155 North Wacker", "AMA Plaza",
            "Salesforce Tower", "Lasalle Bank Bldg", "Mesirow Financial Building",
            "Leo Burnett Building", "River Point", "One Illinois Center",
            "900 N Michigan Ave", "Two Illinois Center", "Michigan Plaza",
            "500 W Monroe Street", "525 West Monroe", "NBC Tower", "River Center",
            "100 North Riverside Plaza", "401 N Michigan Ave", "150 N. Michigan Ave",
            "200 N LaSalle", "200 W Monroe St", "230 West Monroe", "The National",
            "Burnham Center", "111 West Jackson", "The Jewelers Building",
            "444 N Michigan Ave", "122 South Michigan", "The LaSalle Wacker Building",
            "AC Nielsen Building", "225 W Washington Street", "Wrigley Bldg - North Tower",
            "800 Fulton Market", "224 South Michigan Avenue", "Dearborn Plaza",
            "Marquette Building", "208 S LaSalle St", "Jewelers Bldg",
            "Reid Murdoch Center", "Wrigley Building", "20 N Michigan Ave",
            "600 W Jackson Blvd", "101 West Grand", "560-566 W Lake St",
            "Franklin Square", "Presidents Plaza 1", "Presidents Plaza 2", "O'Hare Plaza I",
            "O'Hare Plaza I", "300 South Wacker Property LLC", "175 W Jackson Blvd",
            "The Loftrium", "120 North LaSalle", "One East Wacker", "33 N Dearborn St",
            "11 East Adams Building", "333 N Michigan Ave", "Heyworth Bldg",
            "Monroe Building", "111 West Illinois", "180 North Michigan Avenue",
            "Schwab Center", "Columbia Centre III", "30 N Michigan Ave",
            "Cumberland Metro", "430 N Michigan Ave", "250 S Wacker Dr",
            "205 W. Wacker", "640 N LaSalle", "332 S Michigan Ave", "200 West Madison",
            "77 West Wacker Drive", "Citicorp Plaza - 8430", "US Cellular Plaza - 8420",
            "The 8501 Building", "209 W Jackson Blvd", "322 South Green",
            "Central Arts Building", "Cumberland Centre", "Cumberland Centre - Building 1",
            "205 W Randolph St", "Inland Steel Building", "Adlake Bldg",
            "Evangelical Lutheran Church in America", "150 N Wacker", "111 North Wabash",
            "The Rookery", "O'Hare Plaza II", "500 N Michigan Ave", "Olympia Centre",
            "25 E Washington", "550 West Washington", "17 North State",
            "625 N Michigan Ave", "20 S. Clark", "One Magnificent Mile",
            "33 North LaSalle Street", "North Avenue Collection", "600 W Fulton Street",
            "625 W Adams St", "55 W Wacker Dr", "645 North Michigan Building",
            "134 N. LaSalle LLC", "Monadnock Bldg", "Chicago Temple Bldg",
            "22 West Washington", "SP - 414 North Orleans", "Helix Bldg",
            "8 S. Michigan Ave", "820 W Jackson Blvd", "180 North Wabash Building",
            "Jackson-Quincy Court", "Boyce Bldg", "211 West Wacker Drive",
            "Brooks Bldg", "Old Republic Bldg", "SP - 820 North Orleans",
            "One North LaSalle", "100 North LaSalle", "Congress Center",
            "1K Fulton", "Riverworks Phase I - Sara Lee", "Institute Place Lofts",
            "70 East Lake Bldg", "2211 N Elston Ave", "Lasalle Atrium Bldg",
            "Veterans Square", "Illinois Masonic Medical Office Center", "River West Plaza",
            "954 W Washington Blvd", "29 N Wacker Dr", "Avondale Office Center",
            "203 N LaSalle St", "SP - 350 North LaSalle", "325 West Huron Street",
            "700 W Chicago Ave", "850 W Jackson Blvd", "363 W Erie St", "McClurg Bldg",
            "Republic Bank Building", "Harris Bank Bldg", "Thompson Bldg",
            "515 North State Street", "200 West Adams", "Two North LaSalle",
            "123 West Madison", "228 S Wabash Ave", "626 West Jackson",
            "641 West Lake", "55 West Monroe", "CME Center", "Courthouse Place",
            "314 West Superior Street", "309 W Washington St", "SP - 311 West Superior",
            "420 N Wabash Ave", "208 S Jefferson St", "Pontiac Bldg", "Vogue Bldg",
            "57 W Grand Ave", "10 North Dearborn", "118 South Clinton", "224 N Des Plaines St",
            "30 N LaSalle St", "321 North Clark", "The Franklin", "181 West Madison",
            "Michigan Plaza", "One Financial Place", "Civic Opera Bldg", "300 North LaSalle",
            "55 E Monroe St", "The Mart", "One Prudential Plaza", "311 South Wacker Drive",
            "UBS Tower", "110 North Wacker", "BMO Tower", "131 S. Dearborn",
            "Two North Riverside Plaza", "1332 North Halsted", "225 W Ohio TEST",
            "One Congress Center", "360 North Green", "SBC Ameritech", "1020 W Randolph Building",
            "550 West Jackson Building", "231 South LaSalle", "Chicago Title Tower",
            "24 East Washington", "Test data", "Test data", "1000 N Michigan Avenue",
            "1000 N Michigan Avenue", "1000 N Michigan Avenue", "Two Prudential Plaza",
            "300 E Randolph", "860 W Evergreen Ave", "Wacker Plaza", "CME Center",
            "33 West Monroe", "10 South LaSalle", "Canal Station", "200 W Ohio St",
            "220 West Kinzie Building", "151 N Franklin St", "Union Tower", "Page Brothers Bldg",
            "175 W Washington St", "115 South LaSalle", "Triangle Plaza West",
            "Triangle Plaza East", "541 North Fairbanks Bldg", "936 W Fulton Market",
            "1000 N Milwaukee", "Thompson Center", "100 West Kinzie Building",
            "10 W Hubbard Building", "One North State", "One East Superior Bldg",
            "One East Delaware", "Sullivan Center", "500-508 N Clark St", "4323 N Central Ave",
            "4320 W Montrose Ave", "3201 S Halsted St", "2911 N Halsted", "2555 Central Building",
            "901 West Jackson Building", "1200 North Clark Building", "1024 West Kinzie",
            "230 Kinzie", "212 W Kinzie Building", "400 N State St", "211 E. Chicago Ave.",
            "Christy Bldg", "WEb", "1333 North Kingsbury", "Premier Office Center",
            "125 North Halsted", "1200 West Fulton", "118 N Aberdeen", "Fulton Market One",
            "114 West Illinois", "1132 West Fulton Market", "112 South Sangamon",
            "1101 West Lake", "11 West Illinois","New York Jewelers Building", "11 East Illinois", "11 East Hubbard", "The Clark-Adams Building",
            "The Hub Office Building", "55 E Jackson Blvd", "The Reserve Center", "The Goodman Theatre",
            "Columbus Plaza", "415 N Dearborn St", "120 South LaSalle Street", "Wacker Building",
            "Peterson Park Medical & Dental Bldg", "LaSalle-Wacker Building", "222 West Hubbard Street",
            "445 North Wells Street", "372 West Ontario Street", "Chestnut Court",
            "Chicago Transit Authority - 567 W Lake Street", "114 South Racine",
            "Institute of Cultural Affairs - Greenrise", "Customhouse", "2229 South Halsted", "FBI Chicago",
            "440 North Wells Street", "210-220 N Green", "307 S Sangamon St", "840 N Michigan Shops",
            "George W Dunne Cook County Office Building", "Lincoln Village", "840 S Canal St",
            "Chicago Medical Society", "1840 North Clybourn", "40-50 E Chicago St",
            "212 West Superior Street", "2240 W Ogden Avenue", "444 North Wells Street",
            "3633-3645 S State St", "Harper Court", "Riverplace", "400 South Jefferson", "2235 W 13th St",
            "Chicago Transit Authority - 120 N. Racine", "Bridgeview Bank- Uptown", "168 N Clinton St",
            "174 N. Michigan Avenue", "833 West Jackson", "The Knight Building", "The Gateway - 600 S Damen Ave",
            "515 N Dearborn", "75 E Wacker Dr", "168 N Michigan Ave", "Delaware Bldg", "323 N Michigan Ave",
            "178 W Randolph St", "174 W Randolph St", "72 E Randolph St", "310 N Michigan Ave",
            "3156 W Columbus", "9 W Washington St", "The Harvard School Bldg", "Randolph Tower",
            "Majestic Office Bldg", "Palmer House Office Center", "180 W Washington St", "Gage Bldg",
            "65-67 E Adams St", "30 S Michigan Ave", "17 N Wabash Ave", "Mentor Center", "Reliance Bldg",
            "9 N Wabash Ave", "73 W Monroe St", "410 S Clark St", "234 S Wabash Ave", "Century Bldg",
            "300 W Adams St", "Plymouth Bldg", "The Moser Building", "Printers Square", "601 S LaSalle St",
            "312 W Randolph St", "40 N Wells St", "175 N Franklin St", "209 West Lake Building",
            "739 S Clark St", "210-212 N Canal St", "555 S Dearborn St", "640-644 S Clark St",
            "223 W Lake St", "308 W Randolph St", "Burnham Park Plaza", "41 W Congress Pky",
            "719-721 S State St", "33 W Jackson Blvd", "318 S Michigan Ave", "531 S Plymouth Ct",
            "5404-5412 N Clark St", "4001 W North Ave", "4707 N Broadway Ave"

    };
}
