package Configurations;

public class ContentQuestions {
    public static String [] contentQuestions = {
            "What is the role of the hypothalamus in the endocrine system?",
            "How does insulin regulate blood sugar levels?",
            "What are the stages of mitosis?",
            "Explain the mechanism of action of antibiotics.",
            "What is the difference between arteries and veins?",
            "How does the immune system respond to a viral infection?",
            "What are the symptoms of Parkinson's disease?",
            "Describe the structure of a neuron.",
            "What are the risk factors for developing cardiovascular disease?",
            "How do antiviral drugs work?",
            "What are the functions of the liver?",
            "What are the different types of anesthesia?",
            "Explain the process of DNA replication.",
            "What is the function of the respiratory system?",
            "How does the menstrual cycle work?",
            "What are the causes of asthma?",
            "Describe the process of blood clotting.",
            "What are the stages of embryonic development?",
            "How does chemotherapy work to treat cancer?",
            "What is the function of the kidneys?",
            "How do vaccines work to prevent disease?",
            "What are the symptoms of diabetes?",
            "Explain the process of protein synthesis.",
            "What is the difference between a virus and a bacterium?",
            "How does the brain interpret sensory information?",
            "What are the effects of smoking on the respiratory system?",
            "Describe the structure of the heart.",
            "What are the causes of obesity?",
            "How do anticoagulant drugs work?",
            "What is the role of the pancreas in digestion?",
            "What are the symptoms of depression?",
            "Explain the process of meiosis.",
            "What are the risk factors for developing cancer?",
            "How does the circulatory system maintain homeostasis?",
            "What is the function of the endocrine system?",
            "What are the different types of white blood cells?",
            "Describe the process of muscle contraction.",
            "What are the symptoms of Alzheimer's disease?",
            "How does the body regulate body temperature?",
            "What are the effects of alcohol on the liver?",
            "Explain the process of photosynthesis.",
            "What are the stages of sleep?",
            "What are the symptoms of schizophrenia?",
            "How does the nervous system control movement?",
            "What is the difference between a bacterial and a viral infection?",
            "What are the risk factors for developing osteoporosis?",
            "Describe the process of fertilization.",
            "What are the functions of the digestive system?",
            "How do painkillers work to relieve pain?",
            "What are the symptoms of anxiety?",
            "Explain the process of evolution by natural selection.",
            "What is the difference between type 1 and type 2 diabetes?",
            "How does the body respond to stress?",
            "What are the effects of high blood pressure on the body?",
            "What are the stages of the cell cycle?",
            "Describe the structure of a DNA molecule.",
            "What are the symptoms of bipolar disorder?",
            "Explain the process of gene expression.",
            "What are the functions of the skeletal system?",
            "How do antibiotics differ from antiviral drugs?",
            "What are the causes of high cholesterol?",
            "What are the effects of malnutrition on the body?",
            "Describe the process of synaptic transmission.",
            "What are the symptoms of epilepsy?",
            "How does the body respond to infection?",
            "What are the risk factors for developing heart disease?",
            "Explain the process of osmosis.",
            "What are the functions of the integumentary system?",
            "What are the effects of air pollution on the respiratory system?",
            "What are the symptoms of multiple sclerosis?",
            "How does the body produce energy?",
            "What are the stages of embryonic development?",
            "Explain the process of blood pressure regulation.",
            "What are the causes of kidney disease?",
            "What are the effects of radiation on the body?",
            "Describe the structure of a virus.",
            "What are the symptoms of stroke?",
            "How does the body maintain fluid balance?",
            "What are the risk factors for developing type 2 diabetes?",
            "Explain the process of DNA transcription.",
            "What are the functions of the lymphatic system?",
            "What are the effects of diabetes on the body?",
            "Describe the process of action potential propagation.",
            "What are the symptoms of liver disease?",
            "How does the body regulate blood pH?",
            "What are the causes of autoimmune diseases?",
            "What are the effects of exercise on the cardiovascular system?",
            "Explain the process of protein folding.",
            "What are the functions of the endocrine glands?",
            "What are the symptoms of thyroid disorders?",
            "How does the body regulate blood pressure?",
            "What are the risk factors for developing lung cancer?",
            "Describe the process of neurotransmitter release.",
            "What are the effects of sleep deprivation on the body?",
            "What are the symptoms of rheumatoid arthritis?",
            "Explain the process of digestion.",
            "What are the functions of the reproductive system?",
            "What are the effects of obesity on health?",
            "How does the body respond to a bacterial infection?",
            "What are the risk factors for developing asthma?",
            "Describe the process of DNA repair.",
            "What are the symptoms of heart failure?",
            "How does the body regulate blood sugar levels?",
            "What are the causes of heart attacks?",
            "Explain the process of cell signaling.",
            "What are the functions of the respiratory system?",
            "What are the effects of stress on health?",
            "Describe the process of muscle contraction.",
            "What are the symptoms of chronic obstructive pulmonary disease?",
            "How does the body regulate body temperature?"
    };
}
