package Configurations;

public class Keywords {
    public static String [] keywords = {
            "wellness", "health", "safety", "eldercare", "hygiene", "prevention", "nursing", "therapy", "rehabilitation", "support",
            "assistance", "protection", "comfort", "firstaid", "nutrition", "exercise", "mentalhealth", "monitoring", "medication", "respite",
            "compassion", "counseling", "physiotherapy", "occupational", "caregiving", "diagnosis", "vaccination", "screening", "telemedicine", "mobility",
            "ergonomics", "sanitation", "disinfection", "chronic", "wellbeing", "awareness", "workplace", "compliance", "treatment", "accessibility",
            "coordination", "empowerment", "preventive", "autonomy", "selfcare", "injuryprevention", "posture", "mentalclarity", "balance", "visioncare",
            "dentalcare", "hydration", "stressrelief", "relaxation", "audiology", "prosthetics", "meditation", "alternative", "herbal", "physical",
            "recovery", "cognitive", "elderly", "independence", "advocacy", "infection", "exerciseprogram", "dementia", "arthritis", "chiropractic",
            "palliative", "supportive", "pharmacy", "coordination", "biomechanics", "flexibility", "healthliteracy", "mentalresilience", "visiontesting",
            "diseaseprevention", "burnout", "healthmonitor", "respiratory", "insulin", "painmanagement", "footcare", "pressureulcers", "sensory",
            "infectioncontrol", "publichealth", "emotionalcare", "careplan", "rehab", "occupationalhealth", "patientrights", "accommodation", "empathy",
            "hospice", "chroniccare", "postoperative", "emergency", "fitness", "allergycare", "wellbeingcoaching", "immunization", "healthpromotion",
            "dermatology", "fatiguemanagement", "diabetes", "cardiaccare", "stroke", "mobilityaid", "geriatrics", "musclesupport", "cardiology",
            "pediatrics", "geriatricsupport", "painsupport", "sleephygiene", "vaccineawareness", "recoveryplan", "physio", "medicinesafety",
            "childcare", "pregnancycare", "selfassessment", "adaptive", "endoflife", "counselor", "chronicdisease", "preoperative", "homecare",
            "bloodpressure", "cancerscreening", "antiseptic", "orthotics", "homeopathy", "therapeutic", "evidencebased", "workstress", "cardiovascular",
            "bonehealth", "healthyaging", "visiontherapy", "hospitalsafety", "medicare", "wellnessprogram", "anxietyrelief", "firstaidtraining",
            "orthopedic", "posturalcorrection", "familycare", "immunityboost", "infectionprevention", "dentistry", "bloodsugar", "burnprevention",
            "musclestrength", "cognitivehealth", "mentalfitness", "careethics", "psychologicalcare", "pharmaceutical", "seniorliving", "griefsupport",
            "speechtherapy", "hydrationreminder", "respiratoryhealth", "painrelief", "careguidance", "mindfulness", "physician", "nutritionplan",
            "heartcare", "preventivecare", "anemia", "recoverycenter", "dentistappointment", "autismcare", "skincare", "chronicillness",
            "sleepdisorder", "emergencyresponse", "elderlycare", "sensorytherapy", "relaxationtherapy", "insurancesupport", "orthopedicsupport",
            "weightmanagement", "allergymanagement", "migrainerelief", "muscletherapy", "diabetesmonitoring", "preventivemedicine", "telehealth",
            "injurymanagement", "postinjury", "handhygiene", "occupationaltherapy", "hospicecare", "blooddonation", "emergencycare", "mentalrelaxation",
            "probiotics", "woundcare", "antiviral", "postpartum", "posturalhealth", "gastrocare", "seniorhealth", "spiritualcare", "sportsrehab",
            "cardiopulmonary", "anesthesiology", "vaccinationcampaign", "pediatriccare", "dermatologyclinic", "prostheticlimb", "skinprotection",
            "dehydrationprevention", "fitnessregimen", "recoveryclinic", "preventativehealth", "elderlysupport", "visionpreservation", "nutritioncoaching",
            "gastrointestinal", "stressreduction", "occupationalinjury", "healthtechnology", "musculoskeletal", "socialsupport", "medicinalcare",
            "vitaminsupplement", "handtherapy", "eyeprotection", "teleconsultation", "neuropathy", "cancerawareness", "clinicaltrial", "heartmonitor",
            "respiratorytherapy", "counselingservices", "woundmanagement", "primarycare", "neurological", "orthopedicrehab", "sleeptherapy", "mobilityexercise",
            "elderlysupport", "arthritisrelief", "fluoresponse", "oncology", "burncare", "preventiveprogram", "careethics", "bloodscreening",
            "podiatry", "occupationalrisk", "hormonalcare", "liverhealth", "preoperativecare", "palliativeprogram", "speechassistance", "specialneeds",
            "therapeuticmassage", "medicalsupport", "weightcontrol", "hearingcare", "physicalcondition", "cognitivedecline", "seniorexercise",
            "mentalstate", "psychologicalhealth", "parkinsoncare", "cardiofitness", "allergyalert", "pharmacyservice", "careadvocacy", "digestivehealth",
            "orthopedictherapy", "vascularhealth", "infectionmonitoring", "reproductivehealth", "brainhealth", "bariatric", "thyroidcare", "medicinenutrition",
            "postinjurycare", "geneticcounseling", "environmentalsafety", "ambulatorycare", "tissuehealth", "hospitalitycare", "emotionalhealing",
            "diabeticcare", "palliativeassistance", "dentalhygiene", "psychosocialsupport", "oncologyclinic", "immunehealth", "circulatorycare",
            "preventiveapproach", "neurologicalsupport", "veterancare", "behavioralcare", "seniormobility", "diabeteseducation", "autoimmunecare",
            "mentaldisorder", "clinicalsupport", "nutritionalbalance", "allergytesting", "strokeawareness", "criticalcare", "lifestylecoaching",
            "holisticwellness", "depressioncare", "seniorassistance", "emergencyplanning", "traumacare", "vaccinationreminder", "medicationtracking"
    };
}
