package Configurations;

public class LastNames{
    public static String [] lastNames = {
            "Gonzalez", "Rodriguez", "Gomez", "Fernandez", "Lopez", "Martinez", "Perez", "Garcia", "Sanchez", "Romero",
            "Torres", "Ramirez", "Hernandez", "Ruiz", "Jimenez", "Diaz", "Moreno", "Alvarez", "Munioz", "Gutierrez",
            "Vargas", "Castanio", "Ortega", "Silva", "Nuniez", "Molina", "Castro", "Rojas", "Medina", "Cruz",
            "Navarro", "Cabrera", "Mendoza", "Soto", "Guerrero", "Ortiz", "Delgado", "Rios", "Chavez",
            "Mejia", "Vega", "Avila", "Acosta", "Miranda", "Fuentes", "Campos", "Correa", "Estrada", "Gallardo",
            "Velasco", "Montoya", "Penia", "Rivas", "Quintero", "Barrera", "Cortes", "Aguirre", "Blanco",
            "Padilla", "Arroyo", "Ramos", "Salas", "Santos", "Arias", "Zamora", "Valencia", "Soler", "Peralta",
            "Rocha", "DelValle", "Salazar", "Esquivel", "Rubio", "Calderon", "Rosales", "Urbina", "Luna", "Escobar",
            "Vera", "Orozco", "Villalobos", "Duarte", "Ochoa", "Zuniga", "Rangel", "Aranda", "Vidal", "Barajas",
            "Saucedo", "Becerra", "Cervantes", "Velazquez", "Landa", "Carranza", "Carrillo", "Lara", "DelRio",
            "Andrade", "Arellano", "Avalos", "Camacho", "Cordova", "Cordero", "Fajardo", "Garrido", "Lomeli", "Olivares",
            "Sepulveda", "Mora", "Rico", "Cedillo", "Leon", "Mejia", "Noriega", "Arriaga", "Salcedo", "Arizmendi",
            "Benitez", "Gallegos", "Marquez", "Loaiza", "Aguero", "Baez", "Carrasco", "Delarosa", "Lugo", "Paredes",
            "Quezada", "Villanueva", "Ballesteros", "Bautista", "Pacheco", "Quintana", "Trejo", "Zarate", "Alcala", "Alarcon",
            "Altamirano", "Armenta", "Ayala", "Baeza", "Borrego", "Bustamante", "Carbajal", "Cardenas", "Cisneros", "Escamilla",
            "Escobedo", "Farina", "Galvan", "Garibay", "Garzon", "Giron", "Granados", "Gurrola", "Jauregui", "Jurado",
            "Ledesma", "Maciel", "Manriquez", "Montes", "Negrete", "Nogales", "Olivo", "Ornelas", "Peralta", "Pinedo",
            "Ponce", "Quesada", "Quintanar", "Ramirez", "Resendiz", "Reyes", "Sarabia", "Sarmiento", "Serna", "Sierra",
            "Suarez", "Tijerina", "Tinoco", "Ulloa", "Valdes", "Valdez", "Vargas", "Vazquez", "Venegas", "Villarreal",
            "Zepeda", "Zuniga", "Arguello", "Caro", "Chavarria", "Durazo", "Echeverria", "Estrada", "Frias", "Funes",
            "Godoy", "Guevara", "Haro", "Hurtado", "Landa", "Munguia", "Naranjo", "Ocana", "Orellana", "Palomino",
            "Parra", "Pina", "Polanco", "Ponce", "Quiroz", "Rebolledo", "Rosado", "Rosas", "Salvador", "Sanchez",
            "Santana", "Santos", "Sepulveda", "Solis", "Solorzano", "Tamayo", "Tejada", "Terrazas", "Teran", "Toledo",
            "Trevio", "Trujillo", "Vallejo", "Velazco", "Yanez", "Zavala", "Abrego", "Aguilar", "Aguilera", "Alcaraz",
            "Alfaro", "Amador", "Aragon", "Barraza", "Barron", "Becerra", "Becerro", "Briones", "Canales", "Carballo",
            "Carmona", "Casanova", "Castellanos", "Castellon", "Cervantes", "Cisneros", "Colin", "Covarrubias", "Cuellar", "Delarosa",
            "Diaz", "Dominguez", "Encarnacion", "Encinas", "Escalante", "Esquivel", "Espinoza", "Figueroa", "Flores", "Frias",
            "Funes", "Gaitan", "Gallegos", "Galvan", "Garay", "Gardea", "Garibay", "Garzon", "Gavilanes", "Gonzalo",
            "Granados", "Guerrero", "Gurrola", "Hernandez", "Huerta", "Ibarra", "Islas", "Jauregui", "Jurado", "Lemus",
            "Leal", "Licea", "Lozada", "Lozano", "Lucero", "Lujan", "Macias", "Madrigal", "Malagon", "Manriquez",
            "Marin", "Marmolejo", "Marroquin", "Mejia", "Melendez", "Mendoza", "Monroy", "Monrreal", "Montiel", "Montoya",
            "Moreno", "Noriega", "Ordoez", "Orozco", "Ovalle", "Pacheco", "Palacios", "Palomo", "Paredes", "Parra",
            "Pasillas", "Pedraza", "Perez", "Pichardo", "Pinzon", "Ponce", "Porras", "Quiroz", "Quintero", "Rendon",
            "Reynoso", "Rincon", "Rivera", "Rivas", "Robledo", "Robles", "Rodarte", "Rodriguez", "Rojo", "Rosado",
            "Rubio", "Rueda", "Ruiz", "Saavedra", "Salas", "Salcedo", "Salgado", "Salinas", "Salvador", "Sanabria",
            "Sanchez", "Santana", "Santiago", "Santos", "Saucedo", "Serna", "Sierra", "Silva", "Solis", "Solorzano",
            "Soria", "Sosa", "Suarez", "Tamayo", "Tapia", "Tejada", "Terrazas", "Teran", "Toledo", "Torres",
            "Trejo", "Trevio", "Trujillo", "Tijerina", "Tinoco", "Ulloa", "Urbina", "Valdes", "Valdez", "Vargas",
            "Vazquez", "Vega", "Venegas", "Verdugo", "Villanueva", "Villarreal", "Viveros", "Zambrano", "Zamora", "Zarate",
            "Zavala", "Zepeda", "Zubia", "Zuiga", "Acevedo", "Acosta", "Aguilar", "Aguilera", "Alcala", "Alcaraz",
            "Alfaro", "Alonzo", "Amador", "Anaya", "Aragon", "Arellano", "Arenas", "Armenta", "Armijo", "Arrieta",
            "Arriola", "Arteaga", "Avendano", "Ballesteros", "Barajas", "Barragan", "Bautista", "Beltran", "Benitez", "Bermudez",
            "Brito", "Burgos", "Caballero", "Cabrales", "Calvillo", "Camacho", "Campos", "Canales", "Cano", "Carballo",
            "Cardona", "Cardoza", "Carrasco", "Casanova", "Castillo", "Castro", "Cedillo", "Centeno", "Cervantes", "Chavez",
            "Cisneros", "Cordero", "Cordova", "Cornejo", "Coronado", "Cortez", "Cosme", "Cruz", "Cueva", "Davila",
            "Delarosa", "Duarte", "Echeverria", "Encarnacion", "Escamilla", "Escobar", "Escobedo", "Espinosa", "Estrada", "Fajardo",
            "Farias", "Farina", "Figueroa", "Flores", "Frias", "Fuentes", "Gaitan", "Galicia", "Galindo", "Gallardo",
            "Gamboa", "Garcia", "Garibay", "Garza", "Garrido", "Gomez", "Gonzalez", "Gonzalo", "Gonzalo", "Granados",
            "Guerra", "Guillen", "Gutierrez", "Haro", "Hernandez", "Hidalgo", "Huerta", "Ibarra", "Jaime", "Jaimes",
            "Jauregui", "Jimenez", "Jurado", "Ledesma", "Leiva", "Leal", "Licea", "Linares", "Llamas", "Lopez",
            "Lucero", "Lugo", "Lujan", "Maciel", "Madrigal", "Malagon", "Mancilla", "Manriquez", "Manso", "Marquez",
            "Martinez", "Medina", "Melgar", "Mendez", "Meneses", "Mendoza", "Meraz", "Miranda", "Monrreal", "Montano",
            "Monterrey", "Morales", "Moreno", "Naranjo", "Navarrete", "Navarro", "Nieves", "Noriega", "Obregon", "Ochoa",
            "Ocampo", "Olguin", "Olmedo", "Orellana", "Ornelas", "Osorio", "Oviedo", "Pacheco", "Padilla", "Palencia",
            "Pantoja", "Paredes", "Patino", "Pena", "Perales", "Perdomo", "Perez", "Pichardo", "Piedra", "Pinon",
            "Porras", "Portillo", "Posada", "Prado", "Quintero", "Rangel", "Raya", "Rea", "Rebolledo", "Redondo",
            "Reyes", "Reynaga", "Rico", "Rincon", "Rios", "Rivas", "Robles", "Rocha", "Rojas", "Romero",
            "Romo", "Rosado", "Rosas", "Rubio", "Ruiz", "Saavedra", "Salcedo", "Saldaa", "Salinas", "Salmeron",
            "Salvador", "Sanabria", "Sanchez", "Santana", "Santillan", "Santos", "Sauceda", "Serna", "Sierra", "Silva",
            "Solis", "Solorzano", "Sosa", "Tamez", "Tamayo", "Tapia", "Tejada", "Terrazas", "Tinoco", "Toledo",
            "Torres", "Tovar", "Trejo", "Trevio", "Trujillo", "Ulloa", "Urbina", "Urrutia", "Valencia", "Valenzuela",
            "Valles", "Varela", "Vargas", "Vazquez", "Vega", "Venegas", "Verdugo", "Verduzco", "Viana", "Vidal",
            "Viera", "Vigueras", "Villalobos", "Villanueva", "Villegas", "Viveros", "Zambrano", "Zamora", "Zarate", "Zavala"
    };
}