package insumosPeppermint;
import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
import javafx.scene.control.TextField;
import javafx.scene.control.Button;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
public class formularioWorkshop extends Stage  {
    public formularioWorkshop(){
        GridPane grid = new GridPane();
        grid.setHgap(10);
        grid.setVgap(10);
                TextField imagePathJT = new TextField("path image");
                TextField videoPathJT = new TextField("path video");
                TextField titleWorkshopJT = new TextField("title workshop");
                TextField descriptionWorkshopJT = new TextField("description workshop");
                TextField creatorWorkshopJT = new TextField("id creator workshop");
                TextField tagWorkshopJT = new TextField("id tag workshop");
                TextField categoryWorkshopJT = new TextField("id category workshop");
                TextField topicWorkshopJT = new TextField("id topic workshop");
                TextField subTopicWorkshopJT = new TextField("id sub topic workshop");
                TextField targetAudienceWorkshopJT = new TextField("target audience workshop");
                TextField learningObjectivesWorkshopJT = new TextField("learning objectives workshop");
                TextField whatDoYouNeedJT = new TextField("what do you need");
                TextField purposeWorkshopJT = new TextField("id purpose workshop");
                TextField skillsWorkshopJT = new TextField("id skills workshop");
                TextField pysicalActivityWorkshopJT = new TextField("id pysical activity workshop");
                TextField questionWorkshopJT = new TextField("question workshop");
                TextField answerWorkshopJT = new TextField("answer workshop");
                TextField reviewerWorkshopJT = new TextField("id reviewer workshop");
                TextField reviewWorkshopJT = new TextField("review workshop");
                TextField studentWorkshopJT = new TextField("id student workshop");
                TextField descriptionProjectWorkshopJT = new TextField("description project workshop");
                TextField addLinksWorkshopJT = new TextField("add links workshop");
                TextField titleZoomWorkshopJT = new TextField("title zoom workshop");
                TextField deadlineWorkshopJT = new TextField("deadline workshop");
                TextField descriptionZoomWorkshopJT = new TextField("description zoom workshop");
                TextField zoomUrlWorkshopJT = new TextField("zoom url workshop");
                TextField activitiesTItleWorkshopJT = new TextField("activities title workshop");
                TextField activitieDescriptionWorkshopJT = new TextField("activitie description workshop");
                TextField syncUpTitleWorkshopJT = new TextField("syncUp title workshop");
                TextField syncUpDescriptionWorkshopJT = new TextField("syncUp description workshop");
                TextField instructorSoloWithInstructorJT = new TextField("id instructor solo with instructor");
                TextField instructorGroupWithInstructorJT = new TextField("id instructor group with instructor");
                TextField maxStudentsGroupWithInstructorJT = new TextField("max students group with instructor");
                TextField optimaBuddyGroupGroupWithInstructorJT = new TextField("optimal buddy group with instructor");
                TextField maxStudentsGroupJT = new TextField("max students group");
                TextField optimalBuddyGroupGroupJT = new TextField("optimal buddy group");
                TextField estadoJT = new TextField("estado");
                Button save = new Button("Guardar");
                GridPane.setConstraints(imagePathJT, 2, 1);
                GridPane.setConstraints(videoPathJT, 4, 1);
                GridPane.setConstraints(titleWorkshopJT, 2, 2);
                GridPane.setConstraints(descriptionWorkshopJT, 4, 2);
                GridPane.setConstraints(creatorWorkshopJT, 2, 3);
                GridPane.setConstraints(tagWorkshopJT, 4, 3);
                GridPane.setConstraints(categoryWorkshopJT, 2, 4);
                GridPane.setConstraints(topicWorkshopJT, 4, 4);
                GridPane.setConstraints(subTopicWorkshopJT, 2, 5);
                GridPane.setConstraints(targetAudienceWorkshopJT, 4, 5);
                GridPane.setConstraints(learningObjectivesWorkshopJT, 2, 6);
                GridPane.setConstraints(whatDoYouNeedJT, 4, 6);
                GridPane.setConstraints(purposeWorkshopJT, 2, 7);
                GridPane.setConstraints(skillsWorkshopJT, 4, 7);
                GridPane.setConstraints(pysicalActivityWorkshopJT, 2, 8);
                GridPane.setConstraints(questionWorkshopJT, 4, 8);
                GridPane.setConstraints(answerWorkshopJT, 2, 9);
                GridPane.setConstraints(reviewerWorkshopJT, 4, 9);
                GridPane.setConstraints(reviewWorkshopJT, 2, 10);
                GridPane.setConstraints(studentWorkshopJT, 4, 10);
                GridPane.setConstraints(descriptionProjectWorkshopJT, 2, 11);
                GridPane.setConstraints(addLinksWorkshopJT, 4, 11);
                GridPane.setConstraints(titleZoomWorkshopJT, 2, 12);
                GridPane.setConstraints(deadlineWorkshopJT, 4, 12);
                GridPane.setConstraints(descriptionZoomWorkshopJT, 2, 13);
                GridPane.setConstraints(zoomUrlWorkshopJT, 4, 13);
                GridPane.setConstraints(activitiesTItleWorkshopJT, 2, 14);
                GridPane.setConstraints(activitieDescriptionWorkshopJT, 4, 14);
                GridPane.setConstraints(syncUpTitleWorkshopJT, 2, 15);
                GridPane.setConstraints(syncUpDescriptionWorkshopJT, 4, 15);
                GridPane.setConstraints(instructorSoloWithInstructorJT, 2, 16);
                GridPane.setConstraints(instructorGroupWithInstructorJT, 4, 16);
                GridPane.setConstraints(maxStudentsGroupWithInstructorJT, 2, 17);
                GridPane.setConstraints(optimaBuddyGroupGroupWithInstructorJT, 4, 17);
                GridPane.setConstraints(maxStudentsGroupJT, 2, 18);
                GridPane.setConstraints(optimalBuddyGroupGroupJT, 4, 18);
                GridPane.setConstraints(estadoJT, 2, 19);
                GridPane.setConstraints(save, 3, 20);
                save.setOnAction(e -> {
                    try {
                        String url = "jdbc:mysql://localhost:3306/testbdpeppermint?serverTimezone=UTC";
                        String username = "root";
                        String password = "root";
                        Connection CN = DriverManager.getConnection(url, username, password);
                        String imagePath = imagePathJT.getText();
                        String videoPath = videoPathJT.getText();
                        String titleWorkshop = titleWorkshopJT.getText();
                        String descriptionWorkshop = descriptionWorkshopJT.getText();
                        String creatorWorkshop = creatorWorkshopJT.getText();
                        String tagWorkshop = tagWorkshopJT.getText();
                        String categoryWorkshop = categoryWorkshopJT.getText();
                        String topicWorkshop = topicWorkshopJT.getText();
                        String subTopicWorkshop = subTopicWorkshopJT.getText();
                        String targetAudienceWorkshop = targetAudienceWorkshopJT.getText();
                        String learningObjectivesWorkshop = learningObjectivesWorkshopJT.getText();
                        String whatDoYouNeed = whatDoYouNeedJT.getText();
                        String purposeWorkshop = purposeWorkshopJT.getText();
                        String skillsWorkshop = skillsWorkshopJT.getText();
                        String pysicalActivityWorkshop = pysicalActivityWorkshopJT.getText();
                        String questionWorkshop = questionWorkshopJT.getText();
                        String answerWorkshop = answerWorkshopJT.getText();
                        String reviewerWorkshop = reviewerWorkshopJT.getText();
                        String reviewWorkshop = reviewWorkshopJT.getText();
                        String studentWorkshop = studentWorkshopJT.getText();
                        String descriptionProjectWorkshop = descriptionProjectWorkshopJT.getText();
                        String addLinksWorkshop = addLinksWorkshopJT.getText();
                        String titleZoomWorkshop = titleZoomWorkshopJT.getText();
                        String deadlineWorkshop = deadlineWorkshopJT.getText();
                        String descriptionZoomWorkshop = descriptionZoomWorkshopJT.getText();
                        String zoomUrlWorkshop = zoomUrlWorkshopJT.getText();
                        String activitiesTItleWorkshop = activitiesTItleWorkshopJT.getText();
                        String activitieDescriptionWorkshop = activitieDescriptionWorkshopJT.getText();
                        String syncUpTitleWorkshop = syncUpTitleWorkshopJT.getText();
                        String syncUpDescriptionWorkshop = syncUpDescriptionWorkshopJT.getText();
                        String instructorSoloWithInstructor = instructorSoloWithInstructorJT.getText();
                        String instructorGroupWithInstructor = instructorGroupWithInstructorJT.getText();
                        String maxStudentsGroupWithInstructor = maxStudentsGroupWithInstructorJT.getText();
                        String optimaBuddyGroupGroupWithInstructor = optimaBuddyGroupGroupWithInstructorJT.getText();
                        String maxStudentsGroup = maxStudentsGroupJT.getText();
                        String optimalBuddyGroupGroup = optimalBuddyGroupGroupJT.getText();
                        String estado = estadoJT.getText();
                        String insertSql = "INSERT INTO datoscrearworkshopcompleto (`imagePath`,`videoPath`,`titleWorkshop`,`descriptionWorkshop`,`creatorWorkshop`,`tagWorkshop`,`categoryWorkshop`,`topicWorkshop`,`subTopicWorkshop`,`targetAudienceWorkshop`,`learningObjectivesWorkshop`,`whatDoYouNeed`,`purposeWorkshop`,`skillsWorkshop`,`pysicalActivityWorkshop`,`questionWorkshop`,`answerWorkshop`,`reviewerWorkshop`,`reviewWorkshop`,`studentWorkshop`,`descriptionProjectWorkshop`,`addLinksWorkshop`,`titleZoomWorkshop`,`deadlineWorkshop`,`descriptionZoomWorkshop`,`zoomUrlWorkshop`,`activitiesTItleWorkshop`,`activitieDescriptionWorkshop`,`syncUpTitleWorkshop`,`syncUpDescriptionWorkshop`,`instructorSoloWithInstructor`,`instructorGroupWithInstructor`,`maxStudentsGroupWithInstructor`,`optimaBuddyGroupGroupWithInstructor`,`maxStudentsGroup`,`optimalBuddyGroupGroup`,`estado`) VALUES(" + "'" + imagePath + "'" + "," +
                                "'" + videoPath + "'" + "," + "'" + titleWorkshop + "'" + "," + "'" + descriptionWorkshop + "'" + "," + "'" + creatorWorkshop + "'" + "," + "'" + tagWorkshop + "'" + "," + "'" + categoryWorkshop + "'" + "," + "'" + topicWorkshop + "'" + "," + "'" + subTopicWorkshop + "'" + "," +
                                "'" + targetAudienceWorkshop + "'" + "," + "'" + learningObjectivesWorkshop + "'" + "," + "'" + whatDoYouNeed + "'" + "," + "'" + purposeWorkshop + "'" + "," + "'" + skillsWorkshop + "'" + "," + "'" + pysicalActivityWorkshop + "'" + "," +
                                "'" + questionWorkshop + "'" + "," + "'" + answerWorkshop + "'" + "," + "'" + reviewerWorkshop + "'" + "," + "'" + reviewWorkshop + "'" + "," + "'" + studentWorkshop + "'" + "," + "'" + descriptionProjectWorkshop + "'" + "," + "'" + addLinksWorkshop + "'" + "," +
                                "'" + titleZoomWorkshop + "'" + "," + "'" + deadlineWorkshop + "'" + "," + "'" + descriptionZoomWorkshop + "'" + "," + "'" + zoomUrlWorkshop + "'" + "," + "'" + activitiesTItleWorkshop + "'" + "," + "'" + activitieDescriptionWorkshop + "'" + "," +
                                "'" + syncUpTitleWorkshop + "'" + "," + "'" + syncUpDescriptionWorkshop + "'" + "," + "'" + instructorSoloWithInstructor + "'" + "," + "'" + instructorGroupWithInstructor + "'" + "," + "'" + maxStudentsGroupWithInstructor + "'" + "," +
                                "'" + optimaBuddyGroupGroupWithInstructor + "'" + "," + "'" + maxStudentsGroup + "'" + "," + "'" + optimalBuddyGroupGroup + "'" + "," + estado + ")";
                        Statement stmt = CN.createStatement();
                        stmt.executeUpdate(insertSql);
                        CN.close();
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                });
        grid.getChildren().add(imagePathJT);
        grid.getChildren().add(videoPathJT);
        grid.getChildren().add(titleWorkshopJT);
        grid.getChildren().add(descriptionWorkshopJT);
        grid.getChildren().add(creatorWorkshopJT);
        grid.getChildren().add(tagWorkshopJT);
        grid.getChildren().add(categoryWorkshopJT);
        grid.getChildren().add(topicWorkshopJT);
        grid.getChildren().add(subTopicWorkshopJT);
        grid.getChildren().add(targetAudienceWorkshopJT);
        grid.getChildren().add(learningObjectivesWorkshopJT);
        grid.getChildren().add(whatDoYouNeedJT);
        grid.getChildren().add(purposeWorkshopJT);
        grid.getChildren().add(skillsWorkshopJT);
        grid.getChildren().add(pysicalActivityWorkshopJT);
        grid.getChildren().add(questionWorkshopJT);
        grid.getChildren().add(answerWorkshopJT);
        grid.getChildren().add(reviewerWorkshopJT);
        grid.getChildren().add(reviewWorkshopJT);
        grid.getChildren().add(studentWorkshopJT);
        grid.getChildren().add(descriptionProjectWorkshopJT);
        grid.getChildren().add(addLinksWorkshopJT);
        grid.getChildren().add(titleZoomWorkshopJT);
        grid.getChildren().add(deadlineWorkshopJT);
        grid.getChildren().add(descriptionZoomWorkshopJT);
        grid.getChildren().add(zoomUrlWorkshopJT);
        grid.getChildren().add(activitiesTItleWorkshopJT);
        grid.getChildren().add(activitieDescriptionWorkshopJT);
        grid.getChildren().add(syncUpTitleWorkshopJT);
        grid.getChildren().add(syncUpDescriptionWorkshopJT);
        grid.getChildren().add(instructorSoloWithInstructorJT);
        grid.getChildren().add(instructorGroupWithInstructorJT);
        grid.getChildren().add(maxStudentsGroupWithInstructorJT);
        grid.getChildren().add(optimaBuddyGroupGroupWithInstructorJT);
        grid.getChildren().add(maxStudentsGroupJT);
        grid.getChildren().add(optimalBuddyGroupGroupJT);
        grid.getChildren().add(estadoJT);
        grid.getChildren().add(save);
        ScrollPane scrollPane = new ScrollPane(grid);
        Scene scene = new Scene(scrollPane,400,400);
        setScene(scene);
    }
    public static void main(String[]args){
        Application.launch();
    }
}
