package Peppermint;
import javafx.scene.Scene;
import javafx.scene.control.ButtonType;
import javafx.scene.control.ScrollPane;
import javafx.scene.layout.GridPane;
import javafx.stage.Stage;
public class interfacePropiedadesEstilosYposicionamiento extends interfaceElements{
    @Override
    public void start(Stage stage) {
        stage.setTitle("Bot creator");
        //PROPIEDADES
        consoleTextArea.setEditable(false);
        scrollPane.setHbarPolicy(ScrollPane.ScrollBarPolicy.AS_NEEDED);
        scrollPane.setVbarPolicy(ScrollPane.ScrollBarPolicy.AS_NEEDED);
        grid.setHgap(3);
        grid.setVgap(10);
        //ESTILOS
        crearWorkshop.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        enrollWorkshop.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearArticle.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearClub.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearTechnique.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearClubEvent.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearTaxonomy.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearTag.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearLesson.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearSegment.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        crearUsuario.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        enviarSolicitudDeAmistad.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        joinClub.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        generarPostClub.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        deneterCasoDePrueba.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        execute.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        removerDeLaCola.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        generarInviteGuest.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        enviarRecomendaciones.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        unirMultiplesWorkshop.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        unirMultiplesClub.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        recomendarUsuarios.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        validarDominios.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        buttonexecuteEnviarActivity.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        buttonexecuteResponderActivity.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        guardarBookmark.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        likePost.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        suiteBasica.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        scrollPane.setStyle(" -fx-text-fill: #FFFFFF; -fx-control-inner-background:#000000;");
        comboBox.setStyle("-fx-background-color: #99D0C2;");
        ayuda.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        guardarBookmark.setStyle("-fx-text-fill: #FFFFFF; -fx-background-color: #008A66;");
        cuadroDeAyudas.setEditable(false);
        cuadroDeAyudas.setText(" INSTRUCCIONES BASICAS DE USO: \n 1-Seleccionar el ambiente en el campo 'seleccionar ambiente' \n 2-Introducir cantidad de executionDetails en el campo 'executionDetails' \n 3-Hacer click en una funcion o en varias, por ejemplo 'crear workshop' \n 4-Presionar 'execute' \n\n EN CASO DE AGREGAR POR ERROR UNA FUNCION A LA COLA DE EJECUCION: \n 1-Click en el checkbox de la funcion \n 2-Click en remover de la cola \n\n COMO execute LAS CONFIGURACIONES AVANZADAS \n 1-Seleccionar el ambiente \n 2-Introducir cantidad de executionDetails \n 3-Hacer CLICK DERECHO sobre la funcion a execute \n 4-En la ventana emergente introducir los datos deseados \n 5-Hacer click en el boton 'execute' de la ventana emergente");
        //positionAMIENTO
        GridPane.setConstraints(comboBox,2,1);
        GridPane.setConstraints(executionDetailstf,2,2);
        GridPane.setConstraints(execute, 3, 1);
        GridPane.setConstraints(deneterCasoDePrueba,4,1);
        GridPane.setConstraints(removerDeLaCola, 5, 1);
        GridPane.setConstraints(crearWorkshop, 2, 3);
        GridPane.setConstraints(enrollWorkshop, 2, 4);
        GridPane.setConstraints(crearArticle, 2, 5);
        GridPane.setConstraints(crearClub, 2, 6);
        GridPane.setConstraints(crearTechnique, 2, 7);
        GridPane.setConstraints(crearClubEvent, 2, 8);
        GridPane.setConstraints(crearTaxonomy, 2, 9);
        GridPane.setConstraints(crearTag, 2, 10);
        GridPane.setConstraints(crearLesson, 2, 11);
        GridPane.setConstraints(crearSegment, 2, 12);
        GridPane.setConstraints(crearUsuario, 2, 13);
        GridPane.setConstraints(enviarSolicitudDeAmistad, 3, 3);
        GridPane.setConstraints(joinClub, 3, 4);
        GridPane.setConstraints(generarInviteGuest, 3, 5);
        GridPane.setConstraints(generarPostClub, 3, 6);
        GridPane.setConstraints(enviarRecomendaciones, 3, 7);
        GridPane.setConstraints(recomendarUsuarios, 3, 8);
        GridPane.setConstraints(guardarBookmark, 3, 9);
        GridPane.setConstraints(unirMultiplesWorkshop, 3, 10);
        GridPane.setConstraints(unirMultiplesClub, 3, 11);
        GridPane.setConstraints(buttonexecuteEnviarActivity, 3, 12);
        GridPane.setConstraints(buttonexecuteResponderActivity, 3, 13);
        GridPane.setConstraints(validarDominios, 4, 3);
        GridPane.setConstraints(likePost,4,4);
        GridPane.setConstraints(suiteBasica,5,3);
        GridPane.setConstraints(scrollPane,1,15,7,15);
        GridPane.setConstraints(ayuda,5,13);
        //AGREGAR ELEMENTOS
        grid.getChildren().add(comboBox);
        grid.getChildren().add(executionDetailstf);
        grid.getChildren().add(deneterCasoDePrueba);
        grid.getChildren().add(execute);
        grid.getChildren().add(removerDeLaCola);
        grid.getChildren().add(crearWorkshop);
        grid.getChildren().add(enrollWorkshop);
        grid.getChildren().add(crearArticle);
        grid.getChildren().add(crearClub);
        grid.getChildren().add(crearTechnique);
        grid.getChildren().add(crearClubEvent);
        grid.getChildren().add(crearTaxonomy);
        grid.getChildren().add(crearTag);
        grid.getChildren().add(crearLesson);
        grid.getChildren().add(crearSegment);
        grid.getChildren().add(crearUsuario);
        grid.getChildren().add(enviarSolicitudDeAmistad);
        grid.getChildren().add(joinClub);
        grid.getChildren().add(generarPostClub);
        grid.getChildren().add(generarInviteGuest);
        grid.getChildren().add(enviarRecomendaciones);
        grid.getChildren().add(guardarBookmark);
        grid.getChildren().add(unirMultiplesClub);
        grid.getChildren().add(unirMultiplesWorkshop);
        grid.getChildren().add(buttonexecuteEnviarActivity);
        grid.getChildren().add(buttonexecuteResponderActivity);
        grid.getChildren().add(validarDominios);
        grid.getChildren().add(recomendarUsuarios);
        grid.getChildren().add(likePost);
        grid.getChildren().add(suiteBasica);
        grid.getChildren().add(scrollPane);
        grid.getChildren().add(ayuda);
        dialog.getDialogPane().setContent(cuadroDeAyudas);
        dialog.getDialogPane().getButtonTypes().addAll(ButtonType.OK);
        comboBox.getItems().add("DEV");
        comboBox.getItems().add("QA");
        comboBox.getItems().add("Local");
        comboBox.setValue("Elegir ambiente");
        Scene scene = new Scene (grid,490, 670);
        stage.setScene(scene);
        stage.show();
    }
}
